import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";



const Home: NextPage = () => {
  const user = useUser()

  const {data, isLoading} = api.posts.getAll.useQuery()

  if(isLoading) return <div>Loading...</div>
  if(!data) return <div>Something went wrong!</div>

  return (
    <>
      <Head>
        <title>Chirp T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className=" h-full w-full border-slate-400 md:max-w-2xl bg-white ">
        <div  className=" border-b border-slate-400 p-4 flex ">
          {!user.isSignedIn && <div className=" flex bg-black justify-center ">SignInButton</div>}
          {user.isSignedIn && <div>SignOutButton</div>}
        </div>
        
        <div className=" flex flex-col ">
          {[...data, ...data]?.map((post) => (
            <div key={post.id} className=" p-8 border-b border-slate-400 " >{post.content}</div>
          ) )}
        </div>
        </div>
      </main>
    </>
  );
};

export default Home;
